### ISSUE TITLE
 套件安裝似乎不太對

### ISSUE THREAD

**Issue by 841020** [huier23/stt-website#2]
@huier23 
你好，我試圖在我電腦端跑此專案，出現一些問題
首先 pip3 install -r requirements.txt
這個command line會出錯
因為專案上沒有requirements.txt 只有requirement.txt
應該是pip freeze 輸出時改到檔名？
https://pip.pypa.io/en/stable/reference/pip_freeze/

接著執行 command line後 出現了 這個錯誤訊息
```
Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt
```
我一開始以為，是我的版本問題(我用python3.6.3開虛擬環境跑此專案)
我在我的電腦用pyenv 安裝 python 版本從3.6.3安裝到3.6.8
又接著試3.7.0~3.7.2
每個版本都開虛擬環境去試著安裝requirements.txt
我也有特別去查django 2.0支援的python版本
https://docs.djangoproject.com/en/2.2/faq/install/
3.6.3應該是沒問題的

後來在stack overview找到解法
https://stackoverflow.com/questions/28167987/python-pip-trouble-installing-from-requirements-txt
pip install --upgrade -r requirements.txt

**Comment by 841020** [comment]
抱歉 今天第一次提issue
不太熟悉
剛剛不小心把issue回覆關掉 
所以我又重開了一個
希望可以得到你的回覆

如果你認為沒問題
我會把我這次的修改提出pull requests請求

我想要可以貢獻github社群QQ 完成第一次pull requests

**Comment by huier23** [comment]
我測試用pip install -r requirement.txt (沒有s) 就可以成功安裝了
我這邊會修改requirement.txt為requirements.txt
謝謝你
